// One-shot vendoring of web fonts from Google Fonts into /public/fonts.
// Run: node scripts/vendor-fonts.mjs   (outputs are committed; re-run only to change families)
// Keeps builds/deploys independent of fonts.googleapis.com at runtime.
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const CSS_URL =
  "https://fonts.googleapis.com/css2" +
  "?family=Martel:wght@400;700;800;900" +
  "&family=Anek+Latin:wdth,wght@75..125,100..800" +
  "&family=Anek+Devanagari:wdth,wght@75..125,100..800" +
  "&family=Anek+Malayalam:wdth,wght@75..125,100..800" +
  "&display=swap";

// Modern UA so the API serves woff2 with unicode-range subsets.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const outDir = path.resolve(import.meta.dirname, "../public/fonts");
const cssOut = path.resolve(import.meta.dirname, "../app/fonts.css");

const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error(`Fonts CSS fetch failed: ${res.status}`);
const css = await res.text();

await mkdir(outDir, { recursive: true });

const blocks = css.match(/\/\*[^*]+\*\/\s*@font-face\s*{[^}]+}/g) ?? [];
if (blocks.length === 0) throw new Error("No @font-face blocks parsed");

let localCss =
  "/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n";
const seen = new Map();

for (const block of blocks) {
  const subset = block.match(/\/\*\s*([\w-]+)\s*\*\//)?.[1] ?? "all";
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*([\d\s]+);/)?.[1]?.trim() ?? "400";
  const stretch = block.match(/font-stretch:\s*([\d.%\s]+);/)?.[1]?.trim();
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!family || !url) continue;

  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${subset}-${weight.replace(/\s+/g, "-")}`;
  let file = `${slug}.woff2`;
  const n = seen.get(slug) ?? 0;
  seen.set(slug, n + 1);
  if (n > 0) file = `${slug}-${n}.woff2`;

  const buf = Buffer.from(
    await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer(),
  );
  await writeFile(path.join(outDir, file), buf);

  localCss += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};${
    stretch ? `font-stretch:${stretch};` : ""
  }font-display:swap;src:url(/fonts/${file}) format('woff2');${
    range ? `unicode-range:${range};` : ""
  }}\n`;
  console.log(`✓ ${file} (${(buf.length / 1024).toFixed(0)} KB)`);
}

await writeFile(cssOut, localCss);
console.log(`\nWrote ${seen.size} faces → app/fonts.css`);
